import { describe,expect,it,vi } from 'vitest';
import * as THREE from 'three';
import { HumanModel } from '../src/anatomy/HumanModel.js';

describe('atomic loading and disposal',()=>{
 it('leaves procedural maps and pickables untouched when staged organs are incomplete',async()=>{const model=new HumanModel(),beforePickables=[...model.pickables],beforeOrgans=new Map(model.organMeshes),root=new THREE.Group(),node=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial());root.add(node);const disposeGeometry=vi.spyOn(node.geometry,'dispose');await expect(model.loadDetailedOrgans(()=>{},async()=>({root,groups:new Map([['heart',[{node,fmaId:'FMA7274'}]]])}))).rejects.toThrow(/Missing semantic organ groups/);expect(model.pickables).toEqual(beforePickables);expect([...model.organMeshes.entries()]).toEqual([...beforeOrgans.entries()]);expect(model.fallbackOrgans.visible).toBe(true);expect(root.parent).toBeNull();expect(disposeGeometry).toHaveBeenCalledOnce();});
 it('ignores and disposes an organ asset that completes after teardown',async()=>{const model=new HumanModel();model.dispose();const root=new THREE.Group(),groups=new Map();for(const [id,count] of Object.entries({stomach:1,liver:1,kidneys:2,lungs:2,heart:1,intestines:1,brain:1})){groups.set(id,Array.from({length:count},(_,i)=>{const node=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial());root.add(node);return {node,fmaId:`FMA${i}`};}));}const result=await model.loadDetailedOrgans(()=>{},async()=>({root,groups}));expect(result.ignored).toBe(true);expect(root.parent).toBeNull();expect(model.organAsset).toBeUndefined();});
 it('disposes an invalid staged skin asset without mutating the fallback',async()=>{const model=new HumanModel(),root=new THREE.Group(),node=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial());root.add(node);const disposeGeometry=vi.spyOn(node.geometry,'dispose');await expect(model.loadScannedSkin(()=>{},async()=>({root,groups:new Map()}))).rejects.toThrow(/skin node is missing/);expect(disposeGeometry).toHaveBeenCalledOnce();expect(model.fallbackSkin.visible).toBe(true);expect(model.skinAsset).toBeUndefined();});
 it('disposes replaced source skin materials after a valid commit',async()=>{const model=new HumanModel(),root=new THREE.Group(),source=new THREE.MeshStandardMaterial(),node=new THREE.Mesh(new THREE.BoxGeometry(),source);root.add(node);const disposeMaterial=vi.spyOn(source,'dispose');await model.loadScannedSkin(()=>{},async()=>({root,groups:new Map([['skin',[{node,fmaId:'FMA7163'}]]])}));expect(disposeMaterial).toHaveBeenCalledOnce();expect(node.material).not.toBe(source);expect(model.fallbackSkin.visible).toBe(false);});
 it('disposes shared resources exactly once even when teardown repeats',()=>{const model=new HumanModel(),mat=model.layers.skeleton.children[0].children[0].material,spy=vi.spyOn(mat,'dispose');model.dispose();model.dispose();expect(spy).toHaveBeenCalledOnce();});
});
